import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"
opacity = 0.92
blur = true
option_as_alt = "Both"

#[font]
##normal.family = "JetBrainsMono Nerd Font"
##normal.family = "MesloLGS Nerd Font Mono"
#normal.family = "DroidSansMono Nerd Font"
##style = Regular
#size = 13.0
#

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

